// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycsaseagjramtrhduxav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljc2FzZWFnanJhbXRyaGR1eGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTQwMDQsImV4cCI6MjA2MDQ5MDAwNH0.3qMExpPV5bzf3yZNJ7rtFqDpaJc7axBXPYBBVhRxg14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);